name: Publish Images to Quay.io
on:
  workflow_dispatch: {}
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'scripts/**'
      - 'manifests/**'
      - 'design/**'
    branches: [ main ] 
  

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  publish-images-to-quay:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Quay login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and Publish Images
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./Dockerfile
         platforms: ${{env.PLATFORMS}}
         push: true
         tags: |
           quay.io/riprasad/hpo:operate-first
    
      